package src.controller;

//An Adapter Pattern says that just "converts the interface of a class into another interface that a client wants".
// (Taken from https://www.javatpoint.com/adapter-pattern)

import view.gui.PaintCanvas;

import javax.swing.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.Point;

public class MouseAdapter extends JPanel implements MouseListener {

    private PaintCanvas paintCanvas;
    private Point startPoint;
    private Point endPoint;

    public MouseAdapter() {
        paintCanvas =new PaintCanvas();
        paintCanvas.addMouseListener(this); //I'm not sure what this "I:" is before this. It pops up when I use the auto-complete
    }

    //Debug Function
    //Output string to console for whenever the mouse does something
    private void actionLog(String action, MouseEvent e) {
        System.out.println(action);
    }
    //End of Debug Function

    //The following stub functions were generated by IntelliJ
    //What is the difference between Mouse Clicked vs Mouse Pressed + Mouse Released?

    @Override
    public void mousePressed(MouseEvent e) {
        actionLog("Mouse Pressed", e);
        startPoint = new Point(e.getX(), e.getY());
        System.out.println(startPoint.toString());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        actionLog("Mouse Clicked", e);
        endPoint = new Point(e.getX(), e.getY());
        System.out.println(endPoint.toString());
    }

    //Remove this function because it seems to do the exact same thing as mouseReleased
    @Override
    public void mouseClicked(MouseEvent e) {
        actionLog("Mouse button Clicked", e);
    }

    //Remove this function because it currently doesn't do anything towards what we need from sprint #1
    @Override
    public void mouseEntered(MouseEvent e) {
        actionLog("Mouse entered drawing area", e);
    }

    //Remove this function because it currently doesn't do anything towards what we need from sprint #1
    @Override
    public void mouseExited(MouseEvent e) {
        actionLog("Mouse exited drawing area", e);
    }
}
